if(CMAKE_C_COMPILER_LAUNCHER OR CMAKE_CXX_COMPILER_LAUNCHER)
  message(STATUS "Configuring SCCache - skipped")
  return()
endif()

find_program(SCCACHE_PROGRAM sccache)
if(SCCACHE_PROGRAM)
  set(CMAKE_C_COMPILER_LAUNCHER ${SCCACHE})
  set(CMAKE_CXX_COMPILER_LAUNCHER ${SCCACHE})
  if(MSVC)
    set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "$<$<CONFIG:Debug,RelWithDebInfo>:Embedded>")
  endif()
  message(STATUS "Configuring SCCache - done")
else()
  message(STATUS "Looking for SCCache - not found")
endif()
