# ref: https://github.com/actions/runner-images
name: amd64 Windows CMake

on:
  push:
    branches:
      - ci
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        cmake: [
          {name: "Ninja", generator: "Ninja", config: Release, build_target: all, test_target: test, install_target: install},
          #{name: "VS26", generator: "Visual Studio 18 2026", config: Release, build_target: ALL_BUILD, test_target: RUN_TESTS, install_target: INSTALL},
          #{name: "VS26", generator: "Visual Studio 18 2026", config: Debug, build_target: ALL_BUILD, test_target: RUN_TESTS, install_target: INSTALL},
        ]
      fail-fast: false
    name: amd64•Windows•CMake(${{matrix.cmake.name}},${{matrix.cmake.config}})
    runs-on: windows-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.11

      # Extract and inject MSVC environment variables
      - name: Set up MSVC x64
        if: ${{matrix.cmake.generator == 'Ninja'}}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - uses: actions/checkout@v7
      - name: Check CMake
        run: |
          cmake --version
          cmake -G || true
      - name: Configure
        run: >
          cmake -S. -Bbuild
          -G "${{matrix.cmake.generator}}"
          -DCMAKE_BUILD_TYPE=${{matrix.cmake.config}}
          -DCMAKE_CONFIGURATION_TYPES=${{matrix.cmake.config}}
          -DCMAKE_INSTALL_PREFIX=install
      - name: Build
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target ${{matrix.cmake.build_target}}
          -v -j2
      - name: Test
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target ${{matrix.cmake.test_target}}
          -v
      - name: Install
        run: >
          cmake --build build
          --config ${{matrix.cmake.config}}
          --target ${{matrix.cmake.install_target}}
          -v

  amd64_windows_cmake:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v7
