# ref: https://github.com/docker-library/official-images
name: amd64 Web CMake

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  Distros:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check docker
      run: |
        docker info
        docker buildx ls
    - name: Build env image
      run: make --directory=ci web_env
    - name: Build devel project
      run: make --directory=ci web_devel
    - name: Build project
      run: make --directory=ci web_build
    - name: Test project
      run: make --directory=ci web_test
