name: amd64 FreeBSD CMake

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  # Only macos runner provide virtualisation with vagrant/virtualbox installed.
  freebsd:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v4
    - name: vagrant version
      run: Vagrant --version
    - name: VirtualBox version
      run: virtualbox -h
    - name: Build
      run: make --directory=ci freebsd_build
