# ref: https://toolchains.bootlin.com/
name: mips64 Toolchain CMake

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  mips64:
    strategy:
      matrix:
        targets: [
          # https://go.dev/doc/install/source#environment
          mips64, # alias to mips64-r6
          mips64el, # alias to mips64el-r6
          mips64-r6, # codescape
          mips64el-r6, # codescape
          mips64-r2, # codescape
          mips64el-r2 # codescape
        ]
      fail-fast: false
    name: Linux•Toolchain ${{matrix.targets}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build env stage
      run: make --directory=ci toolchain_${{matrix.targets}}_env
    - name: Build devel stage
      run: make --directory=ci toolchain_${{matrix.targets}}_devel
    - name: Build toolchain stage
      run: make --directory=ci toolchain_${{matrix.targets}}_toolchain
    - name: Build build stage
      run: make --directory=ci toolchain_${{matrix.targets}}_build
    - name: Build Test stage
      run: make --directory=ci toolchain_${{matrix.targets}}_test
